# Smart Hospital Appointment No Show Analytics

---
## Executive Summary

Across the analyzed dataset, **11.55% of scheduled appointments result in no-shows (1,155 missed slots)**, representing an estimated loss of **Rs 703,000+ in direct consultation fees** alone. 

### Key Strategic Objectives
* **Implement Targeted Interventions:** Establish proactive communication workflows (SMS/WhatsApp reminders) and smart booking policies to improve appointment compliance.

---

## Problem Statement

> **"Addressing patient no-show trends to maximize and safeguard revenue."**

---

### Strategic Questions Addressed
1. **No-Show Factors:** What key factors drive patient no-shows, and how can we design targeted interventions to improve attendance?

### Installing libraries

In [1]:
import pandas as pd

### About the Dataset

The dataset is sourced from <a href = "https://www.kaggle.com/datasets/sonalshinde123/smart-healthcare-patient-appointment-dataset">Kaggle</a>

In [2]:
# loading csv file in jupyter notebook
df = pd.read_csv('smart_hospital_appointment_dataset.csv')

In [3]:
# glimpse of data
df.head()

,patient_id,age,gender,city,bmi,chronic_disease,appointment_type,department,symptoms,severity_level,...,waiting_time_minutes,previous_appointments,missed_previous_appointments,hospital_rating,emergency_case,patient_satisfaction_score,medicine_cost,test_cost,total_bill,appointment_status
0,PAT_10000,52,Male,Mumbai,19.6,Hypertension,Scheduled,Neurology,Headache,Low,...,43,7,2,3.0,0,8.6,869,413,1936.0,Completed
1,PAT_10001,21,Female,Mumbai,25.3,NaN,Scheduled,Neurology,Headache,Low,...,44,11,5,3.5,0,8.8,786,875,1356.6,No Show
2,PAT_10002,51,Female,Bangalore,21.9,NaN,Scheduled,Dermatology,Skin Allergy,Low,...,33,9,0,4.4,0,10.0,466,427,1108.8,No Show
3,PAT_10003,78,Female,Delhi,31.7,NaN,Walk-in,Orthopedics,Joint Pain,Low,...,59,13,3,4.1,0,8.1,921,401,1417.5,Completed
4,PAT_10004,62,Female,Mumbai,24.7,Hypertension,Scheduled,Ophthalmology,Eye Irritation,Low,...,42,4,0,3.5,0,8.9,152,216,746.9,Completed

In [4]:
df.shape

(10000, 26)

### Exploratory Data Analysis

In [5]:
# How many patients are below age 30
df[df['age'] < 30]['patient_id'].count()

np.int64(3294)

In [6]:
# How many patients are below age 30, with severity level 30
df[df['age'] < 30].groupby('severity_level')['patient_id'].nunique()

severity_level
High      1028
Low       1092
Medium    1174
Name: patient_id, dtype: int64

### What key factors drive patient no-shows, and how can we design targeted interventions to improve attendance?

> Question: How to identify "No Show" in dataset? <br>
Answer: Use the appointment status column and filter for "No Show" <br> <br>

In [7]:
# How many appointments are no show
df[df['appointment_status'] == 'No Show']['patient_id'].count()

np.int64(1155)

> Question: What is the overall baseline no show rate? <br>
Answer: Create binary variable to check no show and then calculate mean

In [8]:
df['no_show_binary'] =  df['appointment_status'].apply(lambda x:1 if x == 'No Show' else 0)

In [10]:
df['no_show_binary'].mean() * 100

np.float64(11.55)

> ~ 11.55 % standard benchmark

> <b> How much is missed consulting fee due to 'No Show' appointment?

In [11]:
df[df['appointment_status'] == 'No Show']['consultation_fee'].sum()

np.int64(703091)

> A reminder call before ahead of schedule to prevent Rs 7 lakh loss

> <b> Do patients with missed previous appointments are likely to have no show

In [34]:
df['app_missed_risk_indicator'] = df['missed_previous_appointments'].apply(lambda x : 'Low' if x <= 2 else ('Medium' if x <= 6 else 'High'))

In [48]:
df.groupby('app_missed_risk_indicator').agg(
    total = ('patient_id', 'count'),
    noshowpct = ('no_show_binary', 'mean') 
).sort_values(by = 'noshowpct', ascending = False)

                           total  noshowpct
app_missed_risk_indicator
High                          31   0.322581
Medium                      2013   0.171883
Low                         7956   0.100427

> <b> What is the precentage of missed appointments within patients?

In [16]:
df[df['missed_previous_appointments'] != 0]['patient_id'].count() / df['patient_id'].count() * 100

np.float64(67.9)

> 67% patients have missed atleast one appointment in the past